### ISSUE TITLE
Custom error message not used for custom validator

### ISSUE THREAD

**Issue by Lerosen** [valendres/react-declarative-form#22]
I created the following rule.
```typescript
const notZeroRule: ValidatorRule = (key, values) => {
  const value: string = values[key];
  if (value && value.trim() === '0') {
    return {
      context: ValidatorContext.Danger,
      message: 'some message'
    };
  }
  return undefined;
};
```
It is added to the FormInput using the following props.
```
validatorRules={{
    notZero: true
}}
validatorMessages={{
    required: ERROR_MESSAGES.REQUIRED,
    notZero: 'some other message'
}}
```
For an input value breaking the notZero rule the 'some message' message is shown. If I leave it empty the message defined by ERROR_MESSAGES.REQUIRED is used correctly.

**Comment by valendres** [comment]
Hey @lerosen, thanks for raising this. I've made [a change](https://github.com/valendres/react-declarative-form/commit/24d539f10300750468b9b19f7174ac0445a17539) to address this issue and released it in 2.3.1. 

Let me know if this fix works as expected 🙂
